# Generated by Django 5.1.4 on 2024-12-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JewelryPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ANILLO', 'Anillo'), ('COLGANTE', 'Colgante'), ('ARO', 'Aro')], max_length=10)),
                ('material', models.CharField(choices=[('PLATA', 'Plata'), ('BRONCE', 'Bronce'), ('ORO', 'Oro')], max_length=10)),
                ('year_created', models.IntegerField()),
            ],
        ),
    ]
